version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ouriso/api_yamdb:latest
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/code/static
      - static_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web